name: All services CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Download Go dependencies
        run: go mod download

      - name: Verify code formatting
        run: go fmt ./... && git diff --exit-code

      - name: Build Go application
        run: go build -v ./...

      - name: Run unit tests
        run: go test -v -race -covermode=atomic ./...